DROP SCHEMA public CASCADE;


create sequence seq1 start with 1;
create sequence exseq start with 1;


create table workout(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
user_name varchar(255),
workout_name varchar(255),
date DATE);


create table exercise(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
exercise_name varchar(255),
sets int,
repetitions int,
weight int,
workout_id bigint);

create table workout_Plan(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
plan_name varchar(255)
)

create table plan_Workout(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
workout_name varchar(255),
workout_plan_id bigint);


create table plan_Exercise(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
exercise_name varchar(255),
sets int,
repetitions int,
plan_workout_id bigint);


create table users(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key ,
username varchar(255),
password varchar (255),
);

create table  role(
id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
name varchar(255)
);


ALTER TABLE exercise ADD FOREIGN KEY (workout_id) REFERENCES workout(id);
ALTER TABLE plan_Workout ADD FOREIGN KEY (workout_plan_id) REFERENCES workout_Plan(id);
ALTER TABLE plan_Exercise ADD FOREIGN KEY (plan_workout_id) REFERENCES plan_Workout(id);